"""
Enhanced email templates for Social Media Monitor
Provides rich HTML email templates with styling
"""

from jinja2 import Template
from datetime import datetime
from typing import List, Dict, Any

# Base email template with professional styling
BASE_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ subject }}</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f8fafc;
        }
        .header {
            background: linear-gradient(135deg, #2563EB 0%, #7C3AED 100%);
            color: white;
            padding: 30px;
            border-radius: 12px 12px 0 0;
            text-align: center;
        }
        .header h1 {
            margin: 0;
            font-size: 28px;
            font-weight: 700;
        }
        .header p {
            margin: 10px 0 0 0;
            opacity: 0.9;
            font-size: 16px;
        }
        .content {
            background: white;
            padding: 30px;
            border-radius: 0 0 12px 12px;
            box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
        }
        .brand-section {
            margin-bottom: 30px;
            border-left: 4px solid #2563EB;
            padding-left: 20px;
        }
        .brand-name {
            font-size: 24px;
            font-weight: 600;
            color: #1e293b;
            margin-bottom: 15px;
        }
        .platform-section {
            margin-bottom: 20px;
        }
        .platform-header {
            font-size: 18px;
            font-weight: 600;
            color: #475569;
            margin-bottom: 10px;
            text-transform: capitalize;
        }
        .post-item {
            background: #f8fafc;
            border: 1px solid #e2e8f0;
            border-radius: 8px;
            padding: 15px;
            margin-bottom: 15px;
        }
        .post-content {
            font-size: 14px;
            color: #374151;
            margin-bottom: 10px;
            line-height: 1.5;
        }
        .post-summary {
            font-size: 13px;
            color: #6366f1;
            font-style: italic;
            background: #eef2ff;
            padding: 8px 12px;
            border-radius: 6px;
            border-left: 3px solid #6366f1;
        }
        .metrics {
            display: flex;
            gap: 15px;
            margin-top: 10px;
            font-size: 12px;
            color: #64748b;
        }
        .metric {
            display: flex;
            align-items: center;
            gap: 4px;
        }
        .no-posts {
            text-align: center;
            color: #64748b;
            font-style: italic;
            padding: 20px;
            background: #f1f5f9;
            border-radius: 8px;
        }
        .footer {
            text-align: center;
            margin-top: 30px;
            padding: 20px;
            color: #64748b;
            font-size: 14px;
        }
        .footer a {
            color: #2563EB;
            text-decoration: none;
        }
        .stats-summary {
            background: linear-gradient(135deg, #f0f9ff 0%, #e0f2fe 100%);
            border: 1px solid #0ea5e9;
            border-radius: 8px;
            padding: 20px;
            margin-bottom: 25px;
        }
        .stats-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(120px, 1fr));
            gap: 15px;
            margin-top: 15px;
        }
        .stat-item {
            text-align: center;
        }
        .stat-number {
            font-size: 24px;
            font-weight: 700;
            color: #0369a1;
        }
        .stat-label {
            font-size: 12px;
            color: #64748b;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ title }}</h1>
        <p>{{ subtitle }}</p>
    </div>
    <div class="content">
        {{ content }}
    </div>
    <div class="footer">
        <p>Generated by <a href="#">Social Media Monitor</a> • {{ timestamp }}</p>
        <p>This is an automated report. Please do not reply to this email.</p>
    </div>
</body>
</html>
"""

# Brand report template
BRAND_REPORT_TEMPLATE = """
<div class="stats-summary">
    <h3 style="margin: 0 0 10px 0; color: #0369a1;">📊 Report Summary</h3>
    <p style="margin: 0; color: #475569;">Activity report for the past {{ days }} days</p>
    <div class="stats-grid">
        <div class="stat-item">
            <div class="stat-number">{{ total_posts }}</div>
            <div class="stat-label">Total Posts</div>
        </div>
        <div class="stat-item">
            <div class="stat-number">{{ total_engagement }}</div>
            <div class="stat-label">Total Engagement</div>
        </div>
        <div class="stat-item">
            <div class="stat-number">{{ platforms_count }}</div>
            <div class="stat-label">Platforms</div>
        </div>
    </div>
</div>

{% for brand in brands %}
<div class="brand-section">
    <div class="brand-name">{{ brand.name }}</div>
    
    {% if brand.posts %}
        {% for platform, posts in brand.posts.items() %}
        <div class="platform-section">
            <div class="platform-header">📱 {{ platform }}</div>
            {% if posts %}
                {% for post in posts %}
                <div class="post-item">
                    <div class="post-content">{{ post.content[:200] }}{% if post.content|length > 200 %}...{% endif %}</div>
                    {% if post.summary %}
                    <div class="post-summary">🤖 {{ post.summary }}</div>
                    {% endif %}
                    <div class="metrics">
                        <div class="metric">👍 {{ post.likes }} likes</div>
                        <div class="metric">💬 {{ post.comments }} comments</div>
                        <div class="metric">🔄 {{ post.shares }} shares</div>
                        <div class="metric">😊 {{ post.sentiment }}</div>
                    </div>
                </div>
                {% endfor %}
            {% else %}
                <div class="no-posts">No posts from this platform in the last {{ days }} days</div>
            {% endif %}
        </div>
        {% endfor %}
    {% else %}
        <div class="no-posts">No activity detected for this brand in the last {{ days }} days</div>
    {% endif %}
</div>
{% endfor %}
"""

# Welcome email template
WELCOME_TEMPLATE = """
<div style="text-align: center; margin-bottom: 30px;">
    <h2 style="color: #1e293b; margin-bottom: 15px;">🎉 Welcome to Social Media Monitor!</h2>
    <p style="color: #475569; font-size: 16px;">Your email has been successfully configured for automated reports.</p>
</div>

<div style="background: #f0f9ff; border: 1px solid #0ea5e9; border-radius: 8px; padding: 20px; margin-bottom: 25px;">
    <h3 style="margin: 0 0 15px 0; color: #0369a1;">📧 Email Configuration</h3>
    <p style="margin: 0; color: #475569;"><strong>Report Email:</strong> {{ email }}</p>
    <p style="margin: 10px 0 0 0; color: #475569;"><strong>Report Frequency:</strong> Every 2 days (automatic)</p>
</div>

<div style="background: #f0fdf4; border: 1px solid #22c55e; border-radius: 8px; padding: 20px; margin-bottom: 25px;">
    <h3 style="margin: 0 0 15px 0; color: #15803d;">🚀 What's Next?</h3>
    <ul style="margin: 0; padding-left: 20px; color: #475569;">
        <li>Add brands to monitor using the dashboard</li>
        <li>Receive real-time notifications for new activity</li>
        <li>Get comprehensive reports every 2 days</li>
        <li>View detailed analytics and insights</li>
    </ul>
</div>

<div style="background: #fefce8; border: 1px solid #eab308; border-radius: 8px; padding: 20px;">
    <h3 style="margin: 0 0 15px 0; color: #a16207;">💡 Pro Tips</h3>
    <ul style="margin: 0; padding-left: 20px; color: #475569;">
        <li>Monitor competitor brands to stay ahead</li>
        <li>Track sentiment changes over time</li>
        <li>Use the "Send All Reports Now" feature for instant updates</li>
        <li>Check the dashboard regularly for real-time insights</li>
    </ul>
</div>
"""

# Notification email template
NOTIFICATION_TEMPLATE = """
<div style="background: {{ bg_color }}; border: 1px solid {{ border_color }}; border-radius: 8px; padding: 20px; margin-bottom: 25px;">
    <h3 style="margin: 0 0 15px 0; color: {{ text_color }};">{{ icon }} {{ title }}</h3>
    <p style="margin: 0; color: #475569; font-size: 16px;">{{ message }}</p>
    {% if details %}
    <div style="margin-top: 15px; padding-top: 15px; border-top: 1px solid {{ border_color }};">
        {{ details }}
    </div>
    {% endif %}
</div>
"""

class EmailTemplateManager:
    def __init__(self):
        self.base_template = Template(BASE_TEMPLATE)
        self.brand_report_template = Template(BRAND_REPORT_TEMPLATE)
        self.welcome_template = Template(WELCOME_TEMPLATE)
        self.notification_template = Template(NOTIFICATION_TEMPLATE)
    
    def generate_brand_report(self, brands_data: List[Dict[str, Any]], days: int = 2) -> str:
        """Generate a comprehensive brand report email"""
        
        # Calculate summary statistics
        total_posts = sum(len(brand.get('posts', [])) for brand in brands_data)
        total_engagement = 0
        platforms = set()
        
        # Process brands data for template
        processed_brands = []
        for brand_data in brands_data:
            brand_posts = brand_data.get('posts', [])
            
            # Group posts by platform
            platform_posts = {}
            for post in brand_posts:
                platform = post.get('platform', 'unknown')
                platforms.add(platform)
                if platform not in platform_posts:
                    platform_posts[platform] = []
                platform_posts[platform].append(post)
                
                # Add to total engagement
                total_engagement += post.get('likes', 0) + post.get('comments', 0) + post.get('shares', 0)
            
            processed_brands.append({
                'name': brand_data.get('name', 'Unknown Brand'),
                'posts': platform_posts
            })
        
        # Generate content
        content = self.brand_report_template.render(
            brands=processed_brands,
            days=days,
            total_posts=total_posts,
            total_engagement=total_engagement,
            platforms_count=len(platforms)
        )
        
        # Generate full email
        return self.base_template.render(
            title="Social Media Monitor Report",
            subtitle=f"Brand activity summary for the past {days} days",
            subject=f"Social Media Report - {datetime.now().strftime('%B %d, %Y')}",
            content=content,
            timestamp=datetime.now().strftime('%B %d, %Y at %I:%M %p')
        )
    
    def generate_welcome_email(self, email: str) -> str:
        """Generate welcome email for new users"""
        content = self.welcome_template.render(email=email)
        
        return self.base_template.render(
            title="Welcome to Social Media Monitor",
            subtitle="Your monitoring setup is complete!",
            subject="Welcome to Social Media Monitor",
            content=content,
            timestamp=datetime.now().strftime('%B %d, %Y at %I:%M %p')
        )
    
    def generate_notification_email(self, title: str, message: str, 
                                  notification_type: str = "info", details: str = None) -> str:
        """Generate notification email"""
        
        # Define notification styles
        styles = {
            "info": {
                "bg_color": "#f0f9ff",
                "border_color": "#0ea5e9",
                "text_color": "#0369a1",
                "icon": "ℹ️"
            },
            "success": {
                "bg_color": "#f0fdf4",
                "border_color": "#22c55e",
                "text_color": "#15803d",
                "icon": "✅"
            },
            "warning": {
                "bg_color": "#fefce8",
                "border_color": "#eab308",
                "text_color": "#a16207",
                "icon": "⚠️"
            },
            "error": {
                "bg_color": "#fef2f2",
                "border_color": "#ef4444",
                "text_color": "#dc2626",
                "icon": "❌"
            }
        }
        
        style = styles.get(notification_type, styles["info"])
        
        content = self.notification_template.render(
            title=title,
            message=message,
            details=details,
            **style
        )
        
        return self.base_template.render(
            title="Social Media Monitor Notification",
            subtitle=title,
            subject=f"Social Media Monitor - {title}",
            content=content,
            timestamp=datetime.now().strftime('%B %d, %Y at %I:%M %p')
        )
    
    def generate_brand_added_email(self, brand_name: str, profiles: List[Dict[str, Any]]) -> str:
        """Generate email notification when a new brand is added"""
        details = f"""
        <h4 style="margin: 0 0 10px 0; color: #374151;">Profiles Found:</h4>
        <ul style="margin: 0; padding-left: 20px; color: #475569;">
        """
        for profile in profiles:
            details += f"<li><strong>{profile['platform'].title()}:</strong> @{profile['name']}</li>"
        details += "</ul>"
        
        return self.generate_notification_email(
            title="New Brand Added",
            message=f"Successfully added '{brand_name}' to your monitoring list. We're now tracking activity across all platforms.",
            notification_type="success",
            details=details
        )

# Global template manager instance
email_template_manager = EmailTemplateManager()

